sonar.projectKey=arohitu_revcloud-blueprint-extension
sonar.organization=arohitu

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=Revcloud Blueprint
sonar.projectVersion=1.0.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=apps/vscode-extension/src
sonar.tests=apps/vscode-extension/src/__tests__

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Language
sonar.typescript.lcov.reportPaths=coverage/lcov.info

# Exclusions
sonar.exclusions=**/__tests__/**,**/__mocks__/**,**/node_modules/**,**/coverage/**,**/out/**,**/*.test.ts

# Test inclusions
sonar.test.inclusions=**/__tests__/**/*.test.ts

# Coverage exclusions
sonar.coverage.exclusions=**/__tests__/**,**/__mocks__/**,**/node_modules/**,apps/vscode-extension/src/extension.ts
